format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$line_break\
$character\
"""

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

conflicted = "c${count} "
stashed = "s\\$${count} "
deleted = "-d\\[${count}\\]"

staged = "+s${count} "
untracked = "+n\\[${count}\\]"

renamed = "r${count} "
modified = "m\\[${count}\\]"

format = """
([$ahead_behind ](bold green))\
([$staged$untracked ](bold green))\
([$renamed$modified ](bold yellow))\
([$conflicted$stashed$deleted ](bold red))\
"""

